name: 'Windows Build SAM'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: 

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'master'
        submodules: true  # Checkout submodules

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Build SAM
      run: |
        powershell -Command "./CI/windows_sam_build.bat $env:Qt6_DIR"
      shell: powershell
