name: 'Windows Run Engine Tests'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: 

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'master'
        submodules: true  # Checkout submodules

    - name: Build and run engine tests
      run: |
        powershell -Command "./CI/windows_engine_tests.bat"
      shell: powershell
